# Generated by Django 5.1.4 on 2025-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='processing', max_length=20),
        ),
    ]
