# Generated by Django 5.1.4 on 2025-01-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
