# Generated by Django 5.1.4 on 2025-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneruser',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
    ]
