# Generated by Django 5.1.4 on 2025-01-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
