# Generated by Django 5.1.4 on 2025-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userenergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learneruser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
