# Generated by Django 5.1.4 on 2025-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_quiz_shared_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Bootstrap icon class', max_length=50)),
                ('color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
