# Generated by Django 5.1.4 on 2025-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='color',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order position'),
        ),
    ]
