# Generated by Django 5.1.4 on 2025-02-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneruser',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
