# Generated by Django 5.1.4 on 2025-02-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_learneruser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
