# Generated by Django 5.1.4 on 2025-02-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learneruser',
            name='username',
        ),
    ]
